;;; Exercise 1.14
;; Draw the tree illustrating the process generated by the count-change
;; procedure of 1.2.2 in making change for 11 cents.
;; What are the orders of growth of the space and number of steps
;; used by this process as the amount to be changed increases?

;;; Answer:
;; For a better tree look elsewhere ;)
;; scheme@(guile-user)> ,trace (count-change 11)
;; trace: |  (count-change 11)
;; trace: |  (cc 11 5)
;; trace: |  |  (cc 11 4)
;; trace: |  |  |  (cc 11 3)
;; trace: |  |  |  |  (cc 11 2)
;; trace: |  |  |  |  |  (cc 11 1)
;; trace: |  |  |  |  |  |  (cc 11 0)
;; trace: |  |  |  |  |  |  (cc 10 1)
;; trace: |  |  |  |  |  |  |  (cc 10 0)
;; trace: |  |  |  |  |  |  |  (cc 9 1)
;; trace: |  |  |  |  |  |  |  |  (cc 9 0)
;; trace: |  |  |  |  |  |  |  |  (cc 8 1)
;; trace: |  |  |  |  |  |  |  |  |  (cc 8 0)
;; trace: |  |  |  |  |  |  |  |  |  (cc 7 1)
;; trace: |  |  |  |  |  |  |  |  |  |  (cc 7 0)
;; trace: |  |  |  |  |  |  |  |  |  |  (cc 6 1)
;; trace: |  |  |  |  |  |  |  |  |  |  |  (cc 6 0)
;; trace: |  |  |  |  |  |  |  |  |  |  |  (cc 5 1)
;; trace: |  |  |  |  |  |  |  |  |  |  |  |  (cc 5 0)
;; trace: |  |  |  |  |  |  |  |  |  |  |  |  (cc 4 1)
;; trace: |  |  |  |  |  |  |  |  |  |  |  |  |  (cc 4 0)
;; trace: |  |  |  |  |  |  |  |  |  |  |  |  |  (cc 3 1)
;; trace: |  |  |  |  |  |  |  |  |  |  |  |  |  |  (cc 3 0)
;; trace: |  |  |  |  |  |  |  |  |  |  |  |  |  |  (cc 2 1)
;; trace: |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  (cc 2 0)
;; trace: |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  (cc 1 1)
;; trace: |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  (cc 1 0)
;; trace: |  |  |  |  |  (cc 6 2)
;; trace: |  |  |  |  |  |  (cc 6 1)
;; trace: |  |  |  |  |  |  |  (cc 6 0)
;; trace: |  |  |  |  |  |  |  (cc 5 1)
;; trace: |  |  |  |  |  |  |  |  (cc 5 0)
;; trace: |  |  |  |  |  |  |  |  (cc 4 1)
;; trace: |  |  |  |  |  |  |  |  |  (cc 4 0)
;; trace: |  |  |  |  |  |  |  |  |  (cc 3 1)
;; trace: |  |  |  |  |  |  |  |  |  |  (cc 3 0)
;; trace: |  |  |  |  |  |  |  |  |  |  (cc 2 1)
;; trace: |  |  |  |  |  |  |  |  |  |  |  (cc 2 0)
;; trace: |  |  |  |  |  |  |  |  |  |  |  (cc 1 1)
;; trace: |  |  |  |  |  |  |  |  |  |  |  |  (cc 0 1)
;; trace: |  |  |  |  |  |  (cc 1 2)
;; trace: |  |  |  |  |  |  |  (cc 1 1)
;; trace: |  |  |  |  |  |  |  |  (cc 1 0)
;; trace: |  |  |  |  |  |  |  |  (cc 0 1)
;; trace: |  |  |  |  |  |  |  (cc -4 2)
;; trace: |  |  |  |  (cc 1 3)
;; trace: |  |  |  |  |  (cc 1 2)
;; trace: |  |  |  |  |  |  (cc 1 1)
;; trace: |  |  |  |  |  |  |  (cc 1 0)
;; trace: |  |  |  |  |  |  |  (cc 0 1)
;; trace: |  |  |  |  |  |  (cc -4 2)
;; trace: |  |  |  |  |  (cc -9 3)
;; trace: |  |  |  (cc -14 4)
;; trace: |  |  (cc -39 5)

;; On to the more interesting part of the exercise, the complexities.
;; Order of growth of space is straightforward, this is a recursive process,
;; so the order of growth of space will be proportional to the depth
;; of the procedure calls. And that order is Θ(n). The tree depth
;; grows linearly with n in (cc n m).

;; The order of growth of number of steps is a bit more involved.
;; Let's take a look at only using pennies first, i.e. m = 1:
;; (cc n 1) = (+ (cc n 0) (cc (- n d) 1), where d is the coin denomination.
;; Let's denote the order of growth in steps as a function of m and n, F(m, n).
;; F(n, 1) = 1 + F(n - d, 1) = 2 + F(n - 2d, 1), about n/d, so it's Θ(n).

;; Let's now look at the more general case.
;; (cc n m) = (+ (cc n (- m 1))
;;               (cc (- n dm) m) where dm is the denomination for m kinds.
;; = (+
;;      (cc n (- m 1))
;;      (cc (- n dm) (- m 1))
;;      (cc (- n (* 2 dm)) m))
;; = (+
;;      (cc n (- m 1))
;;      (cc (- n dm) (- m 1))
;;      ...
;;      (cc (- n (* fm dm)) (- m 1))
;;      (cc (- n (* (+ fm 1) dm)) m)) where fm is Floor(n/dm).
;; I'll do d and f instead of dm and fm now, for brevity's sake.

;; TODO :P

